#
# Format:
#
# <heroku_san shorthand name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production:
  app: golfstats
  stack: cedar
  config:
    BUNDLE_WITHOUT: "assets:development:test"
    GS_HOST: "golf-stats.net"
    GOOGLE_ANALYTICS: "UA-15021105-1"
    ERROR_PAGE_URL: "http://status.golf-stats.net/error/"
    MAINTENANCE_PAGE_URL: "http://status.golf-stats.net/maintenance/"

staging:
  app: golfstats-staging
  stack: cedar
  config:
    BUNDLE_WITHOUT: "assets:development:test"
    GS_HOST: "golfstats-staging.herokuapp.com"
    ERROR_PAGE_URL: "http://status.golf-stats.net/error/"
    MAINTENANCE_PAGE_URL: "http://status.golf-stats.net/maintenance/"
