local_host: &local_host
  hosts:
    - localhost:27017

development:
  sessions:
    default:
      <<: *local_host
      database: golfstats_development

test:
  sessions:
    default:
      <<: *local_host
      database: golfstats_test

# set these environment variables on your prod server
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
