development:
  host: localhost
  database: golfstats_development

test:
  host: localhost
  database: golfstats_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
