# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development: &default
  secret_key_base: 3eeb74810080ac9f2cbb0eab527af02b9adc58c19f7b2c9eed9c64b36b75f321718a2fa358c2df927dfdaff912cde026b0dee21290c9b4a6ab75f9e0f2f9539d

test:
  <<: *default
  secret_key_base: 1bcac173cbbe24205f21687aa8585603d01d3260f5d00fcbdb85358f68a4faad74b59c7f71bb34690be40fa38710c32f9cf5cf79026b007d60c65f033ca12334

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: &env_configured
  secret_key_base: '<%= ENV["SECRET_KEY_BASE"] %>'
